	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DOUBLE_COLORLESS_ENERGY     ; $07
	const CHIKORITA1                  ; $08
	const CHIKORITA2                  ; $09
	const BAYLEEF1               	  ; $0a
	const BAYLEEF2              	  ; $0b
	const MEGANIUM1                   ; $0c
	const MEGANIUM2                   ; $0d
	const BULBASAUR                   ; $e5
	const IVYSAUR                     ; $e6
	const VENUSAUR                    ; $e7
	const LEDYBA                 	  ; $0e
	const LEDIAN                      ; $0f
	const SPINARAK                    ; $10
	const ARIADOS                     ; $11
	const ZUBAT                       ; $12
	const GOLBAT                      ; $13
	const CROBAT                      ; $14
	const ODDISH                      ; $15
	const GLOOM                       ; $16
	const VILEPLUME                   ; $17
	const BELLOSSOM                   ; $18
	const HOPPIP                      ; $19
	const SKIPLOOM                    ; $1a
	const JUMPLUFF                    ; $1b
	const SUNKERN                     ; $1c
	const SUNFLORA                    ; $1d
	const YANMA                  	  ; $1e
	const PINECO                      ; $1f
	const FORRETRESS                  ; $20
	const SCYTHER                     ; $21
	const SCIZOR                      ; $22
	const HERACROSS                   ; $23
	const CROBAT_S      ; $dc
	const CELEBI_S                    ; $24
	const CYNDAQUIL1                  ; $27
	const CYNDAQUIL2                  ; $28
	const QUILAVA1                    ; $29
	const QUILAVA2                    ; $2a
	const TYPHLOSION1                 ; $2b
	const TYPHLOSION2                 ; $2c
	const MAGBY                       ; $25
	const MAGMAR                      ; $26
	const SLUGMA               	  ; $2d
	const MAGCARGO                    ; $2e
	const HOUNDOUR1                   ; $2f
	const HOUNDOUR2                   ; $30
	const HOUNDOOM                    ; $31
	const VULPIX                      ; $e8
	const NINETALES                   ; $e9
	const GROWLITHE                   ; $35
	const ARCANINE                    ; $36
	const PONYTA                      ; $e8
	const RAPIDASH                    ; $e8
	const FLAREON               	  ; $37
	const MOLTRES                     ; $ea
	const ENTEI1                      ; $32
	const ENTEI2                      ; $33
	const HOOH          	          ; $34
	const CHARMANDER             	  ; $38
	const CHARMELEON                  ; $39
	const CHARIZARD_S                 ; $3a
	const TOTODILE1                   ; $40
	const TOTODILE2                   ; $41
	const CROCONAW1                   ; $42
	const CROCONAW2                   ; $43
	const FERALIGATR1                 ; $44
	const FERALIGATR2                 ; $45
	const SQUIRTLE                    ; $eb
	const WARTORTLE                   ; $ec
	const BLASTOISE                   ; $ed
	const OMANYTE               	  ; $3b
	const OMASTAR                	  ; $3c
	const KABUTO              	  ; $3d
	const KABUTOPS              	  ; $3e
	const VAPOREON                    ; $3f
	const MARILL1                     ; $46
	const MARILL2                     ; $47
	const AZUMARILL1                  ; $48
	const AZUMARILL2                  ; $49
	const POLIWAG                     ; $4a
	const POLIWHIRL                   ; $4b
	const POLITOED                    ; $4c
	const WOOPER                      ; $4d
	const QUAGSIRE                    ; $4e
	const QWILFISH                    ; $4f
	const SNEASEL                     ; $50
	const REMORAID                    ; $51
	const OCTILLERY                   ; $52
	const MANTINE                     ; $53
	const HORSEA                      ; $54
	const SEADRA                      ; $55
	const KINGDRA                     ; $56
	const ARTICUNO                    ; $ee
	const SUICUNE                     ; $57
	const MAGIKARP_S                  ; $58
	const GYARADOS_S                  ; $59
	const KINGDRA_S       ; $e2
	const JOLTEON             	  ; $5a
	const CHINCHOU1           	  ; $5b
	const CHINCHOU2                   ; $5c
	const LANTURN1                    ; $5d
	const LANTURN2              	  ; $5e
	const PICHU               	  ; $5f
	const PIKACHU               	  ; $60
	const PIKACHU2                    ; $f4
	const RAICHU               	  ; $61
	const RAICHU2                     ; $f5
	const MAREEP1             	  ; $62
	const MAREEP2           	  ; $63
	const FLAAFFY1           	  ; $64
	const FLAAFFY2      		  ; $65
	const AMPHAROS1   		  ; $66
	const AMPHAROS2                   ; $67
	const MAGNEMITE                   ; $f8
	const MAGNETON                    ; $f9
	const VOLTORB                     ; $f6
	const ELECTRODE                   ; $f7
	const ELEKID              	  ; $68
	const ELECTABUZZ                  ; $69
	const ZAPDOS                      ; $fa
	const RAIKOU            	  ; $6a
	const RAICHU_S         	          ; $6b
	const POLIWRATH                   ; $6c
	const AERODACTYL                  ; $6d
	const SUDOWOODO                   ; $6e
	const GLIGAR             	  ; $6f
	const ONIX            		  ; $70
	const STEELIX            	  ; $71
	const SHUCKLE              	  ; $72
	const SWINUB              	  ; $73
	const PILOSWINE                   ; $74
	const CORSOLA                     ; $75
	const PHANPY1                     ; $76
	const PHANPY2                     ; $77
	const DONPHAN1                    ; $78
	const DONPHAN2                    ; $79
	const MACHOP                      ; $ef
	const MACHOKE                     ; $f0
	const MACHAMP                     ; $f1
	const TYROGUE                     ; $7a
	const HITMONLEE                   ; $7b
	const HITMONCHAN                  ; $7c
	const HITMONTOP                   ; $7d
	const RHYHORN                     ; $f2
	const RHYDON                      ; $f3
	const LARVITAR                    ; $7e
	const PUPITAR                     ; $7f
	const TYRANITAR                   ; $80
	const KABUTOPS_S                  ; $81
	const STEELIX_S                   ; $82
	const TYRANITAR_S                 ; $83
	const GASTLY                      ; $84
	const HAUNTER                     ; $85
	const GENGAR              	  ; $86
	const MEWTWO                      ; $87
	const MEW                	  ; $88
	const NATU                        ; $89
	const XATU                        ; $8a
	const ESPEON1                     ; $8b
	const ESPEON2                     ; $8c
	const UMBREON                 	  ; $8d
	const MURKROW                     ; $8e
	const ABRA                        ; $fb
	const KADABRA                     ; $fc
	const ALAKAZAM                    ; $e4
	const SLOWPOKE                    ; $8f
	const SLOWBRO                     ; $90
	const SLOWKING                	  ; $91
	const MISDREAVUS              	  ; $92
	const UNOWN_A                     ; $93
	const UNOWN_J                  	  ; $94
	const WOBBUFFET                   ; $95
	const GIRAFARIG                   ; $96
	const SMOOCHUM            	  ; $97
	const JYNX                        ; $98
	const CELEBI                      ; $99
	const MEWTWO_S                    ; $9a
	const MEW_S                       ; $9b
	const SNORLAX	                  ; $e0
	const DRATINI                     ; $9c
	const DRAGONAIR                   ; $9d
	const DRAGONITE                   ; $9e
	const SENTRET            	  ; $9f
	const FURRET                      ; $a0
	const HOOTHOOT                    ; $a1
	const NOCTOWL                     ; $a2
	const CLEFFA                      ; $a3
	const CLEFAIRY                    ; $a4
	const CLEFABLE                    ; $a5
	const IGGLYBUFF                   ; $a6
	const JIGGLYPUFF                  ; $a7
	const WIGGLYTUFF                  ; $a8
	const TOGEPI1                     ; $a9
	const TOGEPI2                     ; $aa
	const TOGETIC1                    ; $ab
	const TOGETIC2                    ; $ac
	const AIPOM            		  ; $ad
	const EEVEE            		  ; $ae
	const DUNSPARCE           	  ; $af
	const SNUBBULL                    ; $b0
	const GRANBULL                    ; $b1
	const TEDDIURSA                   ; $b2
	const URSARING                    ; $b3
	const DELIBIRD                    ; $b4
	const SKARMORY                    ; $b5
	const PORYGON                     ; $b6
	const PORYGON_2                   ; $b7
	const STANTLER                    ; $b8
	const SMEARGLE                    ; $b9
	const MILTANK                     ; $ba
	const CHANSEY                     ; $bb
	const BLISSEY                     ; $bc
	const LUGIA                       ; $bd
	const NOCTOWL_S                   ; $be
	const CHARIZARD_C                 ; $bf
	const LUGIA_C                     ; $c0
	const HOOH_C             	  ; $c1
	const CELEBI_C            	  ; $c2
	const SHADOW_LUGIA                ; $c3
	const PROFESSOR_ELM               ; $c4
	const TEAM_ROCKETS_EVIL_DEEDS     ; $c5
	const MAIL_FROM_BILL              ; $c6
	const FOREST_GUARDIAN             ; $c7
	const SEER                        ; $c8
	const POKEMON_FAN_CLUB            ; $c9
	const STAR_PIECE            	  ; $ca
	const POKE_DOLL                   ; $cb
	const FOSSIL_EGG                  ; $cc
	const ENERGY_ARK           	  ; $cd
	const SUPER_ENERGY_RETRIEVAL      ; $ce
	const ENERGY_SEARCH               ; $cf
	const ENERGY_REMOVAL2             ; $d0
	const MASTER_BALL       	  ; $d1
	const SWITCH                      ; $d2
	const POKEMON_NURSE               ; $d3
	const POKE_BALL                   ; $d4
	const SUPER_SCOOP_UP              ; $d5
	const POKEGEAR            	  ; $d6
	const NEW_POKEDEX                 ; $d7
	const STRENGTH_CHARM              ; $d8
	const CRYSTAL_SHARD               ; $d9
	const RUIN_WALL                   ; $da
	const POKEMON_REVERSAL            ; $db
	const POTION                      ; $dd
	const HYPER_POTION                ; $de
	const FULL_HEAL                   ; $df
	const BILLS_MAINTENANCE           ; $e1
	const ARCADE_GAME                 ; $e3
	
DEF NUM_CARDS EQU const_value - 1
